/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package ru.coffeeplanter.minimum;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int button=0x7f040004;
        public static final int item_list=0x7f040000;
        public static final int label_textview=0x7f040002;
        public static final int main_progress=0x7f040001;
        public static final int pin=0x7f040003;
        public static final int progress=0x7f040005;
    }
    public static final class layout {
        public static final int activity_main=0x7f020000;
        public static final int activity_pin=0x7f020001;
    }
    public static final class string {
        /**  AndroidManifest.xml 
         */
        public static final int app_name=0x7f030000;
        public static final int hint_text=0x7f030004;
        public static final int log_in_button_text=0x7f030005;
        public static final int main_activity_title=0x7f030002;
        public static final int pin_activity_title=0x7f030001;
        /**  PinActivity.java 
         */
        public static final int pin_empty_error=0x7f030006;
        public static final int pin_short_error=0x7f030007;
        /**  activity_pin.xml 
         */
        public static final int text_label=0x7f030003;
    }
}
